from __future__ import annotations
import os
from pathlib import Path
import shutil
import subprocess
import pytest
import gimatch

# Patterns, path, ignorecase, matched
CASES = [
    # Literal:
    (["foo"], "foo", False, True),
    (["foo"], "fo", False, False),
    (["foo"], "fooo", False, False),
    (["foo"], "ofoo", False, False),
    (["foo"], "bar", False, False),
    (["foo"], "bar/foo", False, True),
    (["foo"], "bar/baz/foo", False, True),
    (["foo"], "bar/foo/baz", False, True),
    (["foo"], "FOO", False, False),
    (["foo"], "FOO", True, True),
    # Trailing slash:
    (["foo/"], "foo", False, False),
    (["foo/"], "foo/", False, True),
    (["foo/"], "foo/quux", False, True),
    (["foo/"], "bar/foo", False, False),
    (["foo/"], "bar/foo/", False, True),
    (["foo/"], "bar/foo/quux", False, True),
    # Leading & internal slash:
    (["/foo"], "foo", False, True),
    (["/foo"], "bar/foo", False, False),
    (["foo/bar"], "foo/bar", False, True),
    (["foo/bar"], "foo/bar/quux", False, True),
    (["foo/bar"], "quux/foo/bar", False, False),
    (["foo/bar"], "quux/foo/bar/quux", False, False),
    # Question mark:
    (["f?o"], "foo", False, True),
    (["f?o"], "f/o", False, False),
    (["??"], "foo", False, False),
    (["???"], "foo", False, True),
    # Single asterisk:
    (["f*o"], "foo", False, True),
    (["f*o"], "fo", False, True),
    (["f*o"], "fglarcho", False, True),
    (["f*o"], "f/o", False, False),
    (["f*o"], "føo", False, True),
    (["f/*o"], "f/o", False, True),
    (["f/*o"], "f/glarch/o", False, False),
    (["*"], "foo", False, True),
    (["f*"], "foo", False, True),
    (["*f"], "foo", False, False),
    (["*o"], "foo", False, True),
    (["o*"], "foo", False, False),
    (["*foo*"], "foo", False, True),
    (["foo*"], "foo", False, True),
    (["*foo"], "foo", False, True),
    (["*oo"], ".foo", False, True),
    (["*foo"], ".foo", False, True),
    ([".*"], ".foo", False, True),
    (["*ob*a*r*"], "foobar", False, True),
    (["foo*bar"], "foo/quux/bar", False, False),
    (["*/foo"], "bar/foo", False, True),
    (["*/foo"], "quux/bar/foo", False, False),
    (["*/*/*"], "foo", False, False),
    (["*/*/*"], "foo/bar", False, False),
    (["foo/*"], "foo/", False, True),
    (["foo/*"], "foo/bar", False, True),
    (["*/bar*"], "foo/bar", False, True),
    (["*/bar*"], "foo/bar/baz", False, True),
    # Double asterisk:
    (["foo**"], "foo", False, True),
    (["foo**"], "foo/bar/baz", False, True),
    (["foo**bar"], "foobar", False, True),
    (["foo**bar"], "fooquuxbar", False, True),
    (["foo**bar"], "foo/bar", False, False),
    (["foo**bar"], "foo/quux/bar", False, False),
    (["foo/**"], "foo", False, False),
    (["foo/**"], "foo/", False, True),
    (["foo/**"], "foo/bar", False, True),
    (["foo/**"], "quux/foo/bar", False, False),
    (["foo/**bar"], "foo/bar", False, True),
    (["foo/**bar"], "foo/qbar", False, True),
    (["foo/**bar"], "foo/glarch/bar", False, False),
    pytest.param(
        ["foo**/bar"],
        "foo/glarch/bar",
        False,
        True,
        marks=pytest.mark.xfail(reason="Is this a bug in Git?"),
    ),
    (["foo**/bar"], "foo/bar", False, True),
    (["foo**/bar"], "fooq/bar", False, True),
    (["foo/**/bar"], "foo/bar", False, True),
    (["foo/**/bar"], "foo/baz/bar", False, True),
    (["foo/**/bar"], "foo/gnusto/cleesh/bar", False, True),
    (["foo/**/**/bar"], "foo/bar", False, True),
    (["foo/**/**/bar"], "foo/baz/bar", False, True),
    (["foo/**/**/bar"], "foo/gnusto/cleesh/bar", False, True),
    (["**/foo"], "foo", False, True),
    (["**/foo"], "bar/foo", False, True),
    (["**/foo"], "quux/bar/foo", False, True),
    (["**/bar*"], "foo/bar", False, True),
    (["**/bar*"], "foo/bar/baz", False, True),
    (["**/bar/*"], "quux/foo/bar/baz", False, True),
    (["**/bar/*"], "quux/foo/bar/baz/", False, True),
    (["**/bar/**"], "quux/foo/bar/baz/", False, True),
    (["**/**"], "quux/foo/bar/baz", False, True),
    (["**/**/**"], "quux/foo/bar/baz", False, True),
    # Escaping:
    (["f\\oo"], "foo", False, True),
    (["f\\oo"], "f\\oo", False, False),
    (["f\\\\oo"], "f\\oo", False, True),
    (["\\!important"], "!important", False, True),
    (["\\!important"], "important", False, False),
    (["\\#comment"], "#comment", False, True),
    (["\\#comment"], "\\#comment", False, False),
    (["\\*scape"], "*scape", False, True),
    (["\\*scape"], "escape", False, False),
    (["\\*scape"], "scape", False, False),
    (["\\?scape"], "?scape", False, True),
    (["\\?scape"], "escape", False, False),
    (["foo\\*bar"], "foo*bar", False, True),
    (["foo\\*bar"], "foobar", False, False),
    (["foo\\*bar"], "fooquuxbar", False, False),
    (["foo\\*bar"], "foo\\*bar", False, False),
    (["\\x40home"], "@home", False, False),
    (["\\x40home"], "x40home", False, True),
    (["me\\x40home"], "me@home", False, False),
    (["me\\x40home"], "mex40home", False, True),
    (["foo\\", "bar"], "foo", False, False),
    (["foo\\", "bar"], "foo\n", False, False),
    (["foo\\", "bar"], "bar", False, True),
    (["foo\\", "bar"], "foobar", False, False),
    (["foo\\", "bar"], "foo\\bar", False, False),
    (["foo\\", "bar"], "foo\\", False, False),
    (["foo\\\\", "bar"], "foo\\", False, True),
    (["foo\\\\ ", "bar"], "foo\\", False, True),
    (["foo\\\\ ", "bar"], "foo\\ ", False, False),
    (["\\\\"], "\\", False, True),
    (["\\[ab]"], "[ab]", False, True),
    (["\\??\\?b"], "?a?b", False, True),
    (["\\a\\b\\c"], "abc", False, True),
    # Character classes:
    (["[abc]ar"], "bar", False, True),
    (["[abc]ar"], "zar", False, False),
    (["[abc]ar"], "Bar", False, False),
    (["[abc]ar"], "Bar", True, True),
    (["*[ar]?"], "barr", False, True),
    (["*[ar]?"], "bart", False, True),
    (["*[ar]?"], "batr", False, False),
    (["[bar]"], "bar", False, False),
    (["*[!ba]"], "bar", False, True),
    (["*[!ba]"], "bab", False, False),
    (["*[!ba]"], "ba!", False, True),
    (["*[!ba]"], "baz", False, True),
    (["*[ba!]"], "bar", False, False),
    (["*[ba!]"], "bab", False, True),
    (["*[ba!]"], "ba!", False, True),
    (["*[ba!]"], "baz", False, False),
    (["*[!bar]"], "bar", False, False),
    (["b[a-g]r"], "bar", False, True),
    (["b[a-g]r"], "bgr", False, True),
    (["b[a-g]r"], "bfr", False, True),
    (["b[a-g]r"], "bor", False, False),
    (["b[!a-g]r"], "bar", False, False),
    (["b[!a-g]r"], "bgr", False, False),
    (["b[!a-g]r"], "bfr", False, False),
    (["b[!a-g]r"], "bor", False, True),
    (["b[^a-g]r"], "bar", False, False),
    (["b[^a-g]r"], "bgr", False, False),
    (["b[^a-g]r"], "bfr", False, False),
    (["b[^a-g]r"], "bor", False, True),
    (["a[]]b"], "a]b", False, True),
    (["a[]-]b"], "a-b", False, True),
    (["a[]-]b"], "a]b", False, True),
    (["a[]-]b"], "aab", False, False),
    (["a[]a-]b"], "aab", False, True),
    (["]"], "]", False, True),
    (["[!]-]"], "]", False, False),
    (["[!]-]"], "a", False, True),
    (["foo[/]bar"], "foo/bar", False, False),
    (["foo[\\/]bar"], "foo/bar", False, False),
    (["foo[ab/]bar"], "foo/bar", False, False),
    (["foo[^a]bar"], "foo/bar", False, False),
    (["f[^eiu][^eiu][^eiu][^eiu][^eiu]r"], "foo/bar", False, False),
    (["f[^eiu][^eiu][^eiu][^eiu][^eiu]r"], "foo-bar", False, True),
    (["a[c-c]rt"], "acrt", False, True),
    (["[[]ab]"], "[ab]", False, True),
    (["[[:]ab]"], "[ab]", False, True),
    (["[[:digit]ab]"], "[ab]", False, True),
    (["[\\[:]ab]"], "[ab]", False, True),
    (["[a-e-n]"], "j", False, False),
    (["[a-e-n]"], "-", False, True),
    (["[a-e-n]"], "b", False, True),
    (["[-]"], "-", False, True),
    (["[\\\\-^]"], "]", False, True),
    (["[\\\\-^]"], "[", False, False),
    (["[\\-_]"], "-", False, True),
    (["[\\]]"], "]", False, True),
    (["[\\]]"], "\\]", False, False),
    (["[\\]]"], "\\", False, False),
    (["[--A]"], "-", False, True),
    (["[--A]"], "5", False, True),
    (["[ --]"], " ", False, True),
    (["[ --]"], "$", False, True),
    (["[ --]"], "-", False, True),
    (["[ --]"], "0", False, False),
    (["[]-a]"], "[", False, False),
    (["[]-a]"], "^", False, True),
    (["[!]-a]"], "[", False, True),
    (["[!]-a]"], "^", False, False),
    (["[\\1-\\3]"], "2", False, True),
    (["[\\1-\\3]"], "3", False, True),
    (["[\\1-\\3]"], "4", False, False),
    (["[a^bc]"], "^", False, True),
    (["[a-]b]"], "-b]", False, True),
    (["[\\]"], "\\", False, False),
    (["[\\,]"], "\\", False, False),
    (["[\\,]"], ",", False, True),
    (["[\\\\]"], "\\", False, True),
    (["[!\\\\]"], "\\", False, False),
    (["[\\\\,]"], ",", False, True),
    (["[\\\\,]"], "\\", False, True),
    (["[[-\\]]"], "\\", False, True),
    (["[[-\\]]"], "[", False, True),
    (["[[-\\]]"], "]", False, True),
    (["[[-\\]]"], "-", False, False),
    (["[A-Z]"], "a", False, False),
    (["[A-Z]"], "a", True, True),
    (["[A-Z]"], "A", False, True),
    (["[a-z]"], "A", False, False),
    (["[a-z]"], "A", True, True),
    (["[a-z]"], "a", False, True),
    (["[B-Za]"], "A", False, False),
    (["[B-Za]"], "A", True, True),
    (["[B-Za]"], "a", False, True),
    (["[B-a]"], "A", False, False),
    (["[B-a]"], "A", True, True),
    (["[B-a]"], "a", False, True),
    (["[Z-y]"], "z", False, False),
    (["[Z-y]"], "z", True, True),
    (["[Z-y]"], "Z", False, True),
    (["[[:]ab"], ":ab", False, True),
    (["[:]ab"], ":ab", False, True),
    # POSIX character classes:
    (["[[:alnum:]]"], "a", False, True),
    (["[[:alnum:]]"], "A", False, True),
    (["[[:alnum:]]"], "q", False, True),
    (["[[:alnum:]]"], "7", False, True),
    (["[[:alnum:]]"], "$", False, False),
    (["[[:alnum:]]"], "_", False, False),
    (["[[:alpha:]]"], "q", False, True),
    (["[[:alpha:]]"], "Q", False, True),
    (["[[:alpha:]]"], "7", False, False),
    (["[[:blank:]]"], " ", False, True),
    (["[[:blank:]]"], "\t", False, True),
    (["[[:blank:]]"], "\n", False, False),
    (["[[:blank:]]"], "\v", False, False),
    (["[[:cntrl:]]"], "\x7F", False, True),
    (["[[:cntrl:]]"], "\n", False, True),
    (["[[:cntrl:]]"], "\t", False, True),
    (["[[:cntrl:]]"], " ", False, False),
    (["[[:cntrl:]]"], "\\", False, False),
    (["[[:digit:]]"], "1", False, True),
    (["[[:digit:]]"], "a", False, False),
    (["[[:graph:]]"], "q", False, True),
    (["[[:graph:]]"], "Q", False, True),
    (["[[:graph:]]"], "*", False, True),
    (["[[:graph:]]"], "7", False, True),
    (["[[:graph:]]"], " ", False, False),
    (["[[:lower:]]oo"], "foo", False, True),
    (["[[:lower:]]oo"], "ðoo", False, False),
    (["[[:lower:]]oo"], "Foo", True, True),
    (["[[:lower:]]oo"], "foo", True, True),
    (["[[:lower:]]oo"], "FOO", True, True),
    (["[[:print:]]"], "q", False, True),
    (["[[:print:]]"], "Q", False, True),
    (["[[:print:]]"], "*", False, True),
    (["[[:print:]]"], "7", False, True),
    (["[[:print:]]"], " ", False, True),
    (["[[:print:]]"], "\t", False, False),
    (["[[:print:]]"], "\n", False, False),
    (["[[:punct:]]"], "*", False, True),
    (["[[:punct:]]"], "_", False, True),
    (["[[:punct:]]"], "\\", False, True),
    (["[[:punct:]]"], "~", False, True),
    (["[[:punct:]]"], "0", False, False),
    (["[[:punct:]]"], "p", False, False),
    (["[[:punct:]]"], "/", False, False),
    (["[^[:punct:]]"], "/", False, False),
    (["[^[:punct:]]"], "x", False, True),
    (["[[:space:]]"], "\t", False, True),
    (["[[:space:]]"], "\n", False, True),
    # (["[[:space:]]"], "\v", False, True),  # Not matched by Git; bug?
    # (["[[:space:]]"], "\f", False, True),  # Not matched by Git; bug?
    (["[[:space:]]"], "\r", False, True),
    (["[[:space:]]"], " ", False, True),
    (["[[:upper:]]"], "A", False, True),
    (["[[:upper:]]"], "a", False, False),
    (["[[:upper:]]"], "a", True, True),
    (["[[:upper:]]"], "Q", False, True),
    (["[[:xdigit:]]"], "5", False, True),
    (["[[:xdigit:]]"], "f", False, True),
    (["[[:xdigit:]]"], "D", False, True),
    (["[[:xdigit:]]"], "g", False, False),
    (["[[:alpha:]][[:digit:]][[:upper:]]"], "a1B", False, True),
    (["[[:digit:][:upper:][:space:]]"], "a", False, False),
    (["[[:digit:][:upper:][:space:]]"], "a", True, True),
    (["[[:digit:][:upper:][:space:]]"], "A", False, True),
    (["[[:digit:][:upper:][:space:]]"], "1", False, True),
    (["[[:digit:][:upper:][:space:]]"], " ", False, True),
    (["[[:digit:][:upper:][:space:]]"], "*", False, False),
    (["[[:digit:][:punct:][:space:]]"], "*", False, True),
    (["[a-c[:digit:]x-z]"], "5", False, True),
    (["[a-c[:digit:]x-z]"], "b", False, True),
    (["[a-c[:digit:]x-z]"], "y", False, True),
    (["[a-c[:digit:]x-z]"], "q", False, False),
    # Whitespace & comments:
    ([" "], " ", False, False),
    (["#comment"], "#comment", False, False),
    ([" #comment"], " #comment", False, True),
    (["trailing "], "trailing", False, True),
    (["trailing "], "trailing ", False, False),
    (["trailing\\ "], "trailing ", False, True),
    (["trailing\\  "], "trailing ", False, True),
    (["trailing\\  "], "trailing  ", False, False),
    (["trailing\\ \\ "], "trailing  ", False, True),
    (["trailing \\ "], "trailing  ", False, True),
    (["foo\v"], "foo\v", False, True),
    (["foo\v"], "foo", False, False),
    # Negation:
    (["!important"], "!important", False, False),
    (["!important"], "important", False, False),
    (["!important"], "foo", False, False),
    (["foo/", "!bar"], "foo/bar", False, True),
    (["foo", "!bar"], "foo/bar", False, True),
    (["!bar", "foo"], "foo/bar", False, True),
    (["file", "!dir"], "dir/file", False, True),
    (["!dir", "file"], "dir/file", False, True),
    (["*.txt", "!foo.txt"], "foo.txt", False, False),
    (["!foo.txt", "*.txt"], "foo.txt", False, True),
    (["*.txt", "!*.txt/"], "foo.txt", False, True),
    (["*.txt", "!*.txt/"], "foo.txt/", False, False),
    (["/*", "!/foo", "/foo/*", "!/foo/bar"], "foo", False, False),
    (["/*", "!/foo", "/foo/*", "!/foo/bar"], "quux", False, True),
    (["/*", "!/foo", "/foo/*", "!/foo/bar"], "quux/gnusto", False, True),
    (["/*", "!/foo", "/foo/*", "!/foo/bar"], "foo/quux", False, True),
    (["/*", "!/foo", "/foo/*", "!/foo/bar"], "foo/quux/gnusto", False, True),
    (["/*", "!/foo", "/foo/*", "!/foo/bar"], "quux/foo/bar", False, True),
    (["/*", "!/foo", "/foo/*", "!/foo/bar"], "foo/bar", False, False),
    # Invalid patterns:
    ([""], "foo", False, False),
    (["!"], "foo", False, False),
    (["\\"], "\\", False, False),
    (["[!"], "ab", False, False),
    (["[!"], "[!", False, False),
    (["a[]b"], "ab", False, False),
    (["a[]b"], "a[]b", False, False),
    (["ab["], "ab[", False, False),
    (["[-"], "ab", False, False),
    (["[-"], "[", False, False),
    (["[-"], "-", False, False),
    (["[-"], "[-", False, False),
    (["[ab"], "[ab", False, False),
    (["[ab"], "a", False, False),
    (["[^ab"], "[^ab", False, False),
    (["[^ab"], "q", False, False),
    (["[[:XDIGIT:]]"], "5", False, False),
    (["[[:XDIGIT:]]"], "5", True, False),
    (["[[:digit:][:upper:][:spaci:]]"], "1", False, False),
    (["[[::]ab]"], "[ab]", False, False),
    (["[[::]ab]"], "a", False, False),
    (["[[:]ab]"], "a", False, False),
    (["[[::]ab"], ":ab", False, False),
    # Corner cases:
    (["/"], "foo", False, False),
    (["/"], "foo/", False, False),
    (["*"], ".", False, True),
    (["*/"], "./", False, False),
    ([".*"], ".", False, False),
    ([".*"], "./", False, False),
    (["[[:punct:]]"], ".", False, False),
]


@pytest.mark.parametrize("patterns,path,ignorecase,matched", CASES)
def test_match(patterns: list[str], path: str, ignorecase: bool, matched: bool) -> None:
    gi = gimatch.compile(patterns, ignorecase=ignorecase)
    assert gi.match(path) is matched
    if matched and not ignorecase:
        gii = gimatch.compile(patterns, ignorecase=True)
        assert gii.match(path)


@pytest.fixture(scope="module")
def repo(tmp_path_factory: pytest.TempPathFactory) -> Path:
    p = tmp_path_factory.mktemp("repo")
    subprocess.run(["git", "init"], cwd=p, check=True)
    return p


@pytest.mark.skipif(shutil.which("git") is None, reason="Git not installed")
@pytest.mark.parametrize("patterns,path,ignorecase,matched", CASES)
def test_check_against_git(
    repo: Path, patterns: list[str], path: str, ignorecase: bool, matched: bool
) -> None:
    (repo / ".gitignore").write_text(
        "".join(f"{pat}\n" for pat in patterns), encoding="utf-8"
    )
    if path.startswith(":"):
        # Escape pathspec
        path = f"::{path}"
    r = subprocess.run(
        [
            "git",
            "-c",
            f"core.excludesFile={os.devnull}",
            "-c",
            f"core.ignorecase={ignorecase}",
            "check-ignore",
            "-q",
            "--",
            path,
        ],
        cwd=repo,
    )
    assert (r.returncode == 0) is matched
